import type { Metadata } from "next";

import { Montserrat, Poppins  } from "next/font/google";
import "./globals.css";

import Providers from "@/providers";



const monserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "300"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${monserrat.variable} ${poppins.variable} antialiased`}
      >
        <Providers >
        {children}
        </Providers >
      </body>
    </html>
  );
}




